name: Deploy React App to S3

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - master           # Auto trigger on master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}  # Overriding .env file

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload build artifacts
        run: |
          COMMIT_HASH=${GITHUB_SHA::7}
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }}/frontend/main/$COMMIT_HASH/ \
          --delete --cache-control "max-age=0,no-cache,no-store,must-revalidate"
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }}/frontend/main/latest/ \
          --delete --cache-control "max-age=0,no-cache,no-store,must-revalidate"
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }}/ \
          --delete --cache-control "max-age=0,no-cache,no-store,must-revalidate"